### ISSUE TITLE
Forgot to import `librosa` in `asrp.Code2Speech`?

### ISSUE THREAD

**Issue by jeffeuxMartin** [voidful/asrp#1]
<img width="466" alt="image" src="https://user-images.githubusercontent.com/43311603/182021933-69204253-5016-4f7a-a52d-8810e6a382f0.png">

**Comment by voidful** [comment]
fixed(version v0.0.50

**Comment by jeffeuxMartin** [comment]
Thank you. Now I have learned how to pull request :-)
